export { default as Tpost } from "./tpost/tpost";
export { default as Bar} from "./navbar/index";
export {default as Suggested} from "./suggested/index";
export {default as MyTrend} from "./trending/index";
export {default as Publish} from "./publish/index";
export {default as Rell} from "./reel/reel";
export {default as followers} from "./followers/followers";
export {default as Downprof} from "./downprof/downprof"; 
export {default as login} from "./LogIn/LogIn"; 
export {default as singin} from "./Signin/Signin"; 
export {default as downbar} from "./downbar/downbar"; 
export {default as bardisplay} from "./bardisplay/bardisplay";
export {default as Dbar} from "./dbar/dbar"; 
export {default as editprofile} from "./editprofile/editprofile"; 
